#!/usr/bin/env python3
"""Refresh public Bedrock model metadata using the caller's AWS CLI profile.

No inference is performed. Account IDs, ARNs, application profiles, and credentials
are never copied into the generated snapshot. Failed regions remain unverified.
"""
import concurrent.futures
import datetime
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "Sources/Bedrock/Core/Models/BedrockBundledCatalog.swift"
REGIONS = [
    "us-east-1", "us-east-2", "us-west-1", "us-west-2", "ca-central-1", "ca-west-1",
    "sa-east-1", "mx-central-1", "eu-west-1", "eu-west-2", "eu-west-3",
    "eu-central-1", "eu-central-2", "eu-south-1", "eu-south-2", "eu-north-1",
    "ap-east-1", "ap-east-2", "ap-south-1", "ap-south-2", "ap-northeast-1",
    "ap-northeast-2", "ap-northeast-3", "ap-southeast-1", "ap-southeast-2",
    "ap-southeast-3", "ap-southeast-4", "ap-southeast-5", "ap-southeast-6",
    "ap-southeast-7", "af-south-1", "il-central-1", "me-central-1", "me-south-1",
]


def fetch(region):
    results = {}
    for operation in ["list-foundation-models", "list-inference-profiles"]:
        arguments = ["aws", "bedrock", operation, "--region", region, "--output", "json",
                     "--no-cli-pager", "--cli-connect-timeout", "8", "--cli-read-timeout", "15"]
        if operation == "list-inference-profiles":
            arguments += ["--type-equals", "SYSTEM_DEFINED"]
        try:
            result = subprocess.run(arguments, capture_output=True, text=True, timeout=40)
            if result.returncode != 0:
                return region, None
            results[operation] = json.loads(result.stdout)
        except (subprocess.TimeoutExpired, json.JSONDecodeError):
            return region, None
    return region, results


def main():
    entries = {}
    verified = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=5) as pool:
        for region, result in pool.map(fetch, REGIONS):
            if result is None:
                print(f"{region}: metadata unavailable", flush=True)
                continue
            verified.append(region)
            models = result["list-foundation-models"].get("modelSummaries", [])
            profiles = result["list-inference-profiles"].get("inferenceProfileSummaries", [])
            for model in models:
                model_id = model["modelId"]
                if model.get("modelLifecycle", {}).get("status") != "ACTIVE":
                    continue
                entry = entries.setdefault(model_id, {
                    "id": model_id, "name": model.get("modelName", model_id),
                    "provider": model.get("providerName", model_id.split(".")[0]),
                    "inputModalities": model.get("inputModalities", []),
                    "outputModalities": model.get("outputModalities", []),
                    "streaming": model.get("responseStreamingSupported"),
                    "releasedAt": model.get("modelLifecycle", {}).get("startOfLifeTime"),
                    "regions": {},
                })
                model_profiles = sorted(
                    profile["inferenceProfileId"] for profile in profiles
                    if any(item.get("modelArn", "").split("/")[-1] == model_id
                           for item in profile.get("models", []))
                )
                entry["regions"][region] = {
                    "inferenceTypes": model.get("inferenceTypesSupported", []),
                    "profiles": model_profiles,
                }
            print(f"{region}: {len(models)} models, {len(profiles)} system profiles", flush=True)
    if len(verified) < 2:
        raise SystemExit("Too few regions verified; existing snapshot was preserved.")
    payload = json.dumps(sorted(entries.values(), key=lambda item: item["id"]),
                         ensure_ascii=False, separators=(",", ":"))
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    source = (
        "// Generated by scripts/refresh-model-snapshot.py. Public model metadata only.\n"
        "import Foundation\n\n"
        "enum BedrockBundledCatalog {\n"
        f'    static let checkedAt = "{stamp}"\n'
        f"    static let verifiedRegions: [String] = {json.dumps(sorted(verified))}\n"
        "    static let records: [BedrockRegionalModel] = {\n"
        f'        let data = Data(#"""\n{payload}\n"""#.utf8)\n'
        "        do { return try JSONDecoder().decode([BedrockRegionalModel].self, from: data) }\n"
        '        catch { preconditionFailure("Invalid bundled model catalog: \\(error)") }\n'
        "    }()\n}\n"
    )
    OUTPUT.write_text(source)
    print(f"Wrote {len(entries)} active model IDs across {len(verified)} verified regions to {OUTPUT}", flush=True)


if __name__ == "__main__":
    main()
